version: '3'
services:

  influxdb:
    image: influxdb:2.1
    restart: always
    ports:
      - 8086:8086
    volumes:
      - influxdb2_data:/var/lib/influxdb2
      # - ./influxdb2/init:/docker-entrypoint-initdb.d
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_USERNAME} # sourced from .env
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASSWORD} # sourced from .env
      - DOCKER_INFLUXDB_INIT_ORG=fltlog-org
      - DOCKER_INFLUXDB_INIT_BUCKET=fltlog-bucket
      # - DOCKER_INFLUXDB_INIT_RETENTION=  # unset = retain forever

  grafana:
    image: grafana/grafana-oss
    restart: always
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SERVER_PROTOCOL=https
      - GF_SERVER_CERT_FILE=/var/lib/grafana/ssl/grafana.crt
      - GF_SERVER_CERT_KEY=/var/lib/grafana/ssl/grafana.key
  
volumes:
  influxdb2_data:
  grafana_data: